# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wansoft.Survey' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wansoft.Survey
pod 'Alamofire'
pod 'AlamofireObjectMapper', '~> 5.0'
pod 'SideMenu'
pod 'ChameleonFramework'
pod 'Cosmos', '~> 18.0'
pod 'RealmSwift'
pod 'UITextView+Placeholder'
pod 'ReachabilitySwift'
pod 'PPBadgeViewSwift'
pod "KRProgressHUD"
pod "MTBBarcodeScanner"
pod 'RSBarcodes_Swift', '~> 4.2.1'
pod 'CameraBackground'
pod 'EmailValidator'
pod 'MaterialComponents'
pod 'CVCalendar'
end
